x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "medods_test"
  POSTGRES_PASSWORD: "123"
  POSTGRES_USER: "postgres"

services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medods_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  migrate:
    container_name: migrates
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate", 
      "-path", "/migrations",
      "-database", "postgres://postgres:123@db/medods_test?sslmode=disable",
      "up"
    ]

  app:
    build: .
    depends_on:
      - db
      - migrate
    ports:
      - "8080:8080"
  
volumes:
  db_data: