CREATE TABLE sessions
(
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    refresh_hash TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    ip TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used BOOL NOT NULL DEFAULT FALSE
);